server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: openAPI
          uri: http://localhost:${server.port}/
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs/
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth/v3/api-docs
        name: Authorization Service

