version: '3.9'
services:
  liquibase:
    image: liquibase/liquibase:${LIQUIBASE_VERSION:-latest}
    container_name: liquibase
    depends_on:
      - postgres_db
    # Run the liquibase update
    command: ['update']
    environment:
      - "LIQUIBASE_DRIVER=org.postgresql.Driver"
      - "LIQUIBASE_COMMAND_CHANGELOG_FILE=db.docker.changelog.xml"
      - "LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres_db:5432/quiz_db"
      - "LIQUIBASE_COMMAND_USERNAME=postgres"
      - "LIQUIBASE_COMMAND_PASSWORD=postgres"
    volumes:
      - ../../db/src/main/resources/db/changelog/:/liquibase/changelog/
    networks:
      - ${GLOBAL_NETWORK:-services}