version: '3.7'
services:
  postgres_db:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=quiz_db"
    ports:
      - '5432:5432'
    volumes:
#      - "./data/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./containers-data/postgres_db/db-1/data:/var/lib/postgresql/data/"
    networks:
      - ${GLOBAL_NETWORK:-services}