version: '3.9'
services:
  postgres_db:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=quiz_db"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - "./containers-data/postgres_db/db-1/data:/var/lib/postgresql/data/"
    networks:
      - ${GLOBAL_NETWORK:-services}