version: '3.9'
services:
  auth-service:
    image: ${GROUP_ID}/auth.service:${AUTH_SERVICE_VERSION:-latest}
    user: root
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - "SERVER_PORT=8190"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/quiz_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgres"
    networks:
      - ${GLOBAL_NETWORK:-services}
  quiz-service-1:
    image: ${GROUP_ID}/quiz.service:${QUIZ_SERVICE_VERSION:-latest}
    user: root
    depends_on:
      postgres_db:
        condition: service_healthy
#    entrypoint: ['check-auth-server-started.sh']
    environment:
      - "SERVER_PORT=8290"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/quiz_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgres"
    volumes:
      - "./scripts/check-auth-server-started.sh:/usr/local/bin/check-auth-server-started.sh"
    networks:
      - ${GLOBAL_NETWORK:-services}
  gateway-service-1:
    image: ${GROUP_ID}/gateway.service:${GATEWAY_SERVICE_VERSION:-latest}
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - quiz-service-1
    volumes:
      - "./scripts/check-auth-server-started.sh:/usr/local/bin/check-auth-server-started.sh"
    user: root
    environment:
      - "SERVER_PORT=8081"
      - "AUTH-SERVICE_HOST=auth-service"
      - "AUTH-SERVICE_PORT=8190"
      - "QUIZ-SERVICE-1_HOST=quiz-service-1"
      - "QUIZ-SERVICE-1_PORT=8290"
    networks:
      - ${GLOBAL_NETWORK:-services}
  battle-service-1:
    image: ${GROUP_ID}/battle.service:${BATTLE_SERVICE_VERSION:-latest}
    ports:
      - "8085:8085"
    user: root
    depends_on:
      postgres_db:
        condition: service_healthy
    #    entrypoint: ['check-auth-server-started.sh']
    environment:
      - "SOCKET_SERVER_PORT=8085"
      - "SOCKET_SERVER_HOST=0.0.0.0"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/quiz_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgres"
    volumes:
      - "./scripts/check-auth-server-started.sh:/usr/local/bin/check-auth-server-started.sh"
    networks:
      - ${GLOBAL_NETWORK:-services}
  gpt-service-1:
    image: ${GROUP_ID}/gpt.service:${GPT_SERVICE_VERSION:-latest}
    ports:
      - "8095:8095"
    user: root
    depends_on:
      postgres_db:
        condition: service_healthy
    #    entrypoint: ['check-auth-server-started.sh']
    environment:
      - "SERVER_PORT=8095"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/quiz_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgres"
    volumes:
      - "./scripts/check-auth-server-started.sh:/usr/local/bin/check-auth-server-started.sh"
    networks:
      - ${GLOBAL_NETWORK:-services}